"""
izvoz_tekstovi.py
Tekstovi za sadrzaj PDF i Excel izvestaja (zaglavlja tabela, naslovi
sekcija, nazivi Excel listova, zbirne poruke) na svim jezicima
aplikacije. Koristi ga ekrani/ekran_izvoz.py.

Upotreba:
    from servisi import izvoz_tekstovi as iz
    iz.t("h_datum")                              # "Datum" / "Date" / ...
    iz.t("ukupno_servisi", iznos="4500 RSD")     # tekst sa parametrom

Ako neki kljuc ne postoji za izabrani jezik, koristi se srpski.
Kad se doda novi jezik: napravi novi recnik (kopiraj "en" i prevedi) i
upisi ga u TEKSTOVI na dnu fajla.
"""

from servisi import jezici


SR = {
    # --- naslovi izvestaja (koristi _izracunaj_period) ---
    "naslov_dnevno": "Dnevni izvestaj - {datum}",
    "naslov_nedeljno": "Nedeljni izvestaj - {pocetak} do {kraj}",
    "naslov_mesecno": "Mesecni izvestaj - {mesec}",
    "naslov_polug1": "Polugodisnji izvestaj - {godina} (januar-jun)",
    "naslov_polug2": "Polugodisnji izvestaj - {godina} (jul-decembar)",
    "naslov_godisnje": "Godisnji izvestaj - {godina}",
    "period": "Period: {pocetak} do {kraj}",
    "dvotacka": ": ",
    # --- podaci o vozacu ---
    "vozac_ime": "Ime i prezime",
    "vozac_licenca": "Licenca",
    "vozac_telefon": "Telefon",
    "vozac_vozilo": "Vozilo",
    "vozac_tablice": "Tablice",
    # --- naslovi sekcija u PDF-u ---
    "servisi_naslov": "Servisi vozila u periodu",
    "troskovi_naslov": "Ostali troskovi u periodu",
    "potrosnja_naslov": "Potrosnja goriva",
    "gorivo_naslov": "Gorivo - svi unosi u periodu",
    "voznje_naslov": "Voznje u periodu",
    # --- zaglavlja tabela (PDF i Excel) ---
    "h_rbr": "R.br.",
    "h_datum": "Datum",
    "h_vrsta_servisa": "Vrsta servisa",
    "h_kilometraza": "Kilometraza",
    "h_cena": "Cena",
    "h_napomena": "Napomena",
    "h_vrsta": "Vrsta",
    "h_predjeno": "Predjeno (od proslog sipanja)",
    "h_sipano": "Sipano",
    "h_potrosnja": "Potrosnja",
    "h_cena_sipanja": "Cena sipanja",
    "h_litara": "Litara",
    "h_km_pumpa": "Km na pumpi",
    "h_pocetak": "Pocetak",
    "h_kraj": "Kraj",
    "h_adresa_polaska": "Adresa polaska",
    "h_adresa_dolaska": "Adresa dolaska",
    "h_km": "Km",
    "h_tarifa": "Tarifa",
    "h_cena_km": "Cena/km",
    "h_start_taksa": "Start taksa",
    "h_ukupna_cena": "Ukupna cena",
    # --- poruke i zbirovi u PDF-u ---
    "nema_servisa": "Nema unetih servisa u ovom periodu.",
    "ukupno_servisi": "Ukupno potroseno na servise u periodu: {iznos}",
    "nema_troskova": "Nema unetih ostalih troskova u ovom periodu.",
    "ukupno_troskovi": "Ukupno ostalih troskova u periodu: {iznos}",
    "prosek_potrosnje": "Prosecna potrosnja za period: {prosek} l/100km ({litara} l na {km} km)",
    "nema_potrosnje": "Nema izracunate potrosnje za ovaj period - potrebna su bar dva uzastopna sipanja sa upisanom kilometrazom (km na pumpi), pri cemu drugo od njih pada u izabrani period.",
    "ukupno_gorivo": "Ukupno potroseno na gorivo u periodu: {iznos}",
    "ukupno_litara": "Ukupno litara u periodu: {litara} l",
    "nema_goriva": "Nema unetih goriva u ovom periodu.",
    "nema_voznji": "Nema voznji u ovom periodu.",
    "ukupan_broj": "Ukupan broj voznji: {broj}",
    "ukupno_predjeno": "Ukupno predjeno (voznje): {km} km",
    "ukupna_zarada": "Ukupna zarada za period: {iznos}",
    "neto": "Neto (zarada - gorivo - servisi - ostali troskovi): {iznos}",
    # --- jedinice ---
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    # --- Excel: nazivi listova ---
    "sheet_pregled": "Pregled",
    "sheet_voznje": "Voznje",
    "sheet_gorivo": "Gorivo",
    "sheet_servisi": "Servisi",
    "sheet_troskovi": "Troskovi",
    # --- Excel: list Pregled ---
    "podaci_vozaca": "Podaci o vozacu",
    "zbirni_pregled": "Zbirni pregled (formule - vidi ostale listove)",
    "x_ukupno_predjeno": "Ukupno predjeno (voznje)",
    "x_broj_voznji": "Broj voznji",
    "x_bruto": "Bruto zarada (voznje)",
    "x_gorivo": "Gorivo (trosak)",
    "x_litara": "   od toga - litara goriva",
    "x_servisi": "Servisi (trosak)",
    "x_troskovi": "Ostali troskovi",
    "x_neto": "NETO (bruto zarada - gorivo - servisi - ostali troskovi)",
    # --- vrednosti koje app cuva u bazi/json-u (za prikaz) ---
    "tip_benzin": "Benzin",
    "tip_tng": "TNG",
    "trosak_parking": "Parking",
    "trosak_putarina": "Putarina",
    "trosak_pranje": "Pranje",
    "trosak_ostalo": "Ostalo",
    "gps_napomena": "GPS voznja (automatski unos)",
}

EN = {
    "naslov_dnevno": "Daily report - {datum}",
    "naslov_nedeljno": "Weekly report - {pocetak} to {kraj}",
    "naslov_mesecno": "Monthly report - {mesec}",
    "naslov_polug1": "Half-year report - {godina} (January-June)",
    "naslov_polug2": "Half-year report - {godina} (July-December)",
    "naslov_godisnje": "Yearly report - {godina}",
    "period": "Period: {pocetak} to {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Full name",
    "vozac_licenca": "License",
    "vozac_telefon": "Phone",
    "vozac_vozilo": "Vehicle",
    "vozac_tablice": "Plates",
    "servisi_naslov": "Vehicle service in the period",
    "troskovi_naslov": "Other expenses in the period",
    "potrosnja_naslov": "Fuel consumption",
    "gorivo_naslov": "Fuel - all entries in the period",
    "voznje_naslov": "Rides in the period",
    "h_rbr": "No.",
    "h_datum": "Date",
    "h_vrsta_servisa": "Service type",
    "h_kilometraza": "Mileage",
    "h_cena": "Price",
    "h_napomena": "Note",
    "h_vrsta": "Type",
    "h_predjeno": "Distance (since last fill-up)",
    "h_sipano": "Filled",
    "h_potrosnja": "Consumption",
    "h_cena_sipanja": "Fill-up price",
    "h_litara": "Liters",
    "h_km_pumpa": "Pump mileage",
    "h_pocetak": "Start",
    "h_kraj": "End",
    "h_adresa_polaska": "Pickup address",
    "h_adresa_dolaska": "Destination address",
    "h_km": "Km",
    "h_tarifa": "Tariff",
    "h_cena_km": "Price/km",
    "h_start_taksa": "Start fee",
    "h_ukupna_cena": "Total price",
    "nema_servisa": "No service entries in this period.",
    "ukupno_servisi": "Total spent on service in the period: {iznos}",
    "nema_troskova": "No other expenses entered in this period.",
    "ukupno_troskovi": "Total other expenses in the period: {iznos}",
    "prosek_potrosnje": "Average consumption for the period: {prosek} l/100km ({litara} l over {km} km)",
    "nema_potrosnje": "No consumption calculated for this period - at least two consecutive fill-ups with mileage entered (pump mileage) are needed, with the second one falling within the selected period.",
    "ukupno_gorivo": "Total spent on fuel in the period: {iznos}",
    "ukupno_litara": "Total liters in the period: {litara} l",
    "nema_goriva": "No fuel entries in this period.",
    "nema_voznji": "No rides in this period.",
    "ukupan_broj": "Total number of rides: {broj}",
    "ukupno_predjeno": "Total distance (rides): {km} km",
    "ukupna_zarada": "Total earnings for the period: {iznos}",
    "neto": "Net (earnings - fuel - service - other expenses): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Summary",
    "sheet_voznje": "Rides",
    "sheet_gorivo": "Fuel",
    "sheet_servisi": "Service",
    "sheet_troskovi": "Expenses",
    "podaci_vozaca": "Driver details",
    "zbirni_pregled": "Summary (formulas - see the other sheets)",
    "x_ukupno_predjeno": "Total distance (rides)",
    "x_broj_voznji": "Number of rides",
    "x_bruto": "Gross earnings (rides)",
    "x_gorivo": "Fuel (expense)",
    "x_litara": "   of which - liters of fuel",
    "x_servisi": "Service (expense)",
    "x_troskovi": "Other expenses",
    "x_neto": "NET (gross earnings - fuel - service - other expenses)",
    "tip_benzin": "Gasoline",
    "tip_tng": "LPG",
    "trosak_parking": "Parking",
    "trosak_putarina": "Tolls",
    "trosak_pranje": "Washing",
    "trosak_ostalo": "Other",
    "gps_napomena": "GPS ride (automatic entry)",
}

IT = {
    "naslov_dnevno": "Rapporto giornaliero - {datum}",
    "naslov_nedeljno": "Rapporto settimanale - dal {pocetak} al {kraj}",
    "naslov_mesecno": "Rapporto mensile - {mesec}",
    "naslov_polug1": "Rapporto semestrale - {godina} (gennaio-giugno)",
    "naslov_polug2": "Rapporto semestrale - {godina} (luglio-dicembre)",
    "naslov_godisnje": "Rapporto annuale - {godina}",
    "period": "Periodo: dal {pocetak} al {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Nome e cognome",
    "vozac_licenca": "Licenza",
    "vozac_telefon": "Telefono",
    "vozac_vozilo": "Veicolo",
    "vozac_tablice": "Targa",
    "servisi_naslov": "Manutenzione del veicolo nel periodo",
    "troskovi_naslov": "Altre spese nel periodo",
    "potrosnja_naslov": "Consumo di carburante",
    "gorivo_naslov": "Carburante - tutte le voci nel periodo",
    "voznje_naslov": "Corse nel periodo",
    "h_rbr": "N.",
    "h_datum": "Data",
    "h_vrsta_servisa": "Tipo di manutenzione",
    "h_kilometraza": "Chilometraggio",
    "h_cena": "Prezzo",
    "h_napomena": "Note",
    "h_vrsta": "Tipo",
    "h_predjeno": "Percorsi (dall'ultimo rifornimento)",
    "h_sipano": "Rifornito",
    "h_potrosnja": "Consumo",
    "h_cena_sipanja": "Prezzo rifornimento",
    "h_litara": "Litri",
    "h_km_pumpa": "Km al distributore",
    "h_pocetak": "Inizio",
    "h_kraj": "Fine",
    "h_adresa_polaska": "Indirizzo di partenza",
    "h_adresa_dolaska": "Indirizzo di destinazione",
    "h_km": "Km",
    "h_tarifa": "Tariffa",
    "h_cena_km": "Prezzo/km",
    "h_start_taksa": "Tariffa di partenza",
    "h_ukupna_cena": "Prezzo totale",
    "nema_servisa": "Nessuna manutenzione inserita in questo periodo.",
    "ukupno_servisi": "Totale speso in manutenzione nel periodo: {iznos}",
    "nema_troskova": "Nessuna altra spesa inserita in questo periodo.",
    "ukupno_troskovi": "Totale altre spese nel periodo: {iznos}",
    "prosek_potrosnje": "Consumo medio nel periodo: {prosek} l/100km ({litara} l su {km} km)",
    "nema_potrosnje": "Nessun consumo calcolato per questo periodo - servono almeno due rifornimenti consecutivi con chilometraggio inserito (km al distributore), di cui il secondo rientra nel periodo selezionato.",
    "ukupno_gorivo": "Totale speso in carburante nel periodo: {iznos}",
    "ukupno_litara": "Totale litri nel periodo: {litara} l",
    "nema_goriva": "Nessuna voce di carburante in questo periodo.",
    "nema_voznji": "Nessuna corsa in questo periodo.",
    "ukupan_broj": "Numero totale di corse: {broj}",
    "ukupno_predjeno": "Distanza totale (corse): {km} km",
    "ukupna_zarada": "Guadagno totale del periodo: {iznos}",
    "neto": "Netto (guadagno - carburante - manutenzione - altre spese): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Riepilogo",
    "sheet_voznje": "Corse",
    "sheet_gorivo": "Carburante",
    "sheet_servisi": "Manutenzione",
    "sheet_troskovi": "Spese",
    "podaci_vozaca": "Dati del conducente",
    "zbirni_pregled": "Riepilogo generale (formule - vedi gli altri fogli)",
    "x_ukupno_predjeno": "Distanza totale (corse)",
    "x_broj_voznji": "Numero di corse",
    "x_bruto": "Guadagno lordo (corse)",
    "x_gorivo": "Carburante (spesa)",
    "x_litara": "   di cui - litri di carburante",
    "x_servisi": "Manutenzione (spesa)",
    "x_troskovi": "Altre spese",
    "x_neto": "NETTO (guadagno lordo - carburante - manutenzione - altre spese)",
    "tip_benzin": "Benzina",
    "tip_tng": "GPL",
    "trosak_parking": "Parcheggio",
    "trosak_putarina": "Pedaggi",
    "trosak_pranje": "Lavaggio",
    "trosak_ostalo": "Altro",
    "gps_napomena": "Corsa GPS (inserimento automatico)",
}

FR = {
    "naslov_dnevno": "Rapport quotidien - {datum}",
    "naslov_nedeljno": "Rapport hebdomadaire - du {pocetak} au {kraj}",
    "naslov_mesecno": "Rapport mensuel - {mesec}",
    "naslov_polug1": "Rapport semestriel - {godina} (janvier-juin)",
    "naslov_polug2": "Rapport semestriel - {godina} (juillet-décembre)",
    "naslov_godisnje": "Rapport annuel - {godina}",
    "period": "Période : du {pocetak} au {kraj}",
    "dvotacka": " : ",
    "vozac_ime": "Nom et prénom",
    "vozac_licenca": "Licence",
    "vozac_telefon": "Téléphone",
    "vozac_vozilo": "Véhicule",
    "vozac_tablice": "Plaque",
    "servisi_naslov": "Entretien du véhicule sur la période",
    "troskovi_naslov": "Autres dépenses sur la période",
    "potrosnja_naslov": "Consommation de carburant",
    "gorivo_naslov": "Carburant - toutes les entrées de la période",
    "voznje_naslov": "Courses de la période",
    "h_rbr": "N°",
    "h_datum": "Date",
    "h_vrsta_servisa": "Type d'entretien",
    "h_kilometraza": "Kilométrage",
    "h_cena": "Prix",
    "h_napomena": "Remarque",
    "h_vrsta": "Type",
    "h_predjeno": "Parcouru (depuis le dernier plein)",
    "h_sipano": "Plein",
    "h_potrosnja": "Consommation",
    "h_cena_sipanja": "Prix du plein",
    "h_litara": "Litres",
    "h_km_pumpa": "Km à la pompe",
    "h_pocetak": "Début",
    "h_kraj": "Fin",
    "h_adresa_polaska": "Adresse de départ",
    "h_adresa_dolaska": "Adresse d'arrivée",
    "h_km": "Km",
    "h_tarifa": "Tarif",
    "h_cena_km": "Prix/km",
    "h_start_taksa": "Prise en charge",
    "h_ukupna_cena": "Prix total",
    "nema_servisa": "Aucun entretien saisi sur cette période.",
    "ukupno_servisi": "Total dépensé en entretien sur la période : {iznos}",
    "nema_troskova": "Aucune autre dépense saisie sur cette période.",
    "ukupno_troskovi": "Total des autres dépenses sur la période : {iznos}",
    "prosek_potrosnje": "Consommation moyenne sur la période : {prosek} l/100km ({litara} l sur {km} km)",
    "nema_potrosnje": "Aucune consommation calculée pour cette période - il faut au moins deux pleins consécutifs avec kilométrage renseigné (km à la pompe), dont le second tombe dans la période choisie.",
    "ukupno_gorivo": "Total dépensé en carburant sur la période : {iznos}",
    "ukupno_litara": "Total de litres sur la période : {litara} l",
    "nema_goriva": "Aucune entrée de carburant sur cette période.",
    "nema_voznji": "Aucune course sur cette période.",
    "ukupan_broj": "Nombre total de courses : {broj}",
    "ukupno_predjeno": "Distance totale (courses) : {km} km",
    "ukupna_zarada": "Gains totaux pour la période : {iznos}",
    "neto": "Net (gains - carburant - entretien - autres dépenses) : {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Synthèse",
    "sheet_voznje": "Courses",
    "sheet_gorivo": "Carburant",
    "sheet_servisi": "Entretien",
    "sheet_troskovi": "Dépenses",
    "podaci_vozaca": "Données du chauffeur",
    "zbirni_pregled": "Synthèse globale (formules - voir les autres feuilles)",
    "x_ukupno_predjeno": "Distance totale (courses)",
    "x_broj_voznji": "Nombre de courses",
    "x_bruto": "Gains bruts (courses)",
    "x_gorivo": "Carburant (dépense)",
    "x_litara": "   dont - litres de carburant",
    "x_servisi": "Entretien (dépense)",
    "x_troskovi": "Autres dépenses",
    "x_neto": "NET (gains bruts - carburant - entretien - autres dépenses)",
    "tip_benzin": "Essence",
    "tip_tng": "GPL",
    "trosak_parking": "Parking",
    "trosak_putarina": "Péages",
    "trosak_pranje": "Lavage",
    "trosak_ostalo": "Autre",
    "gps_napomena": "Course GPS (saisie automatique)",
}

DE = {
    "naslov_dnevno": "Tagesbericht - {datum}",
    "naslov_nedeljno": "Wochenbericht - {pocetak} bis {kraj}",
    "naslov_mesecno": "Monatsbericht - {mesec}",
    "naslov_polug1": "Halbjahresbericht - {godina} (Januar-Juni)",
    "naslov_polug2": "Halbjahresbericht - {godina} (Juli-Dezember)",
    "naslov_godisnje": "Jahresbericht - {godina}",
    "period": "Zeitraum: {pocetak} bis {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Vor- und Nachname",
    "vozac_licenca": "Lizenz",
    "vozac_telefon": "Telefon",
    "vozac_vozilo": "Fahrzeug",
    "vozac_tablice": "Kennzeichen",
    "servisi_naslov": "Fahrzeugwartung im Zeitraum",
    "troskovi_naslov": "Sonstige Ausgaben im Zeitraum",
    "potrosnja_naslov": "Kraftstoffverbrauch",
    "gorivo_naslov": "Kraftstoff - alle Einträge im Zeitraum",
    "voznje_naslov": "Fahrten im Zeitraum",
    "h_rbr": "Nr.",
    "h_datum": "Datum",
    "h_vrsta_servisa": "Wartungsart",
    "h_kilometraza": "Kilometerstand",
    "h_cena": "Preis",
    "h_napomena": "Notiz",
    "h_vrsta": "Art",
    "h_predjeno": "Gefahren (seit dem letzten Tanken)",
    "h_sipano": "Getankt",
    "h_potrosnja": "Verbrauch",
    "h_cena_sipanja": "Tankpreis",
    "h_litara": "Liter",
    "h_km_pumpa": "Km an der Zapfsäule",
    "h_pocetak": "Start",
    "h_kraj": "Ende",
    "h_adresa_polaska": "Abfahrtsadresse",
    "h_adresa_dolaska": "Zieladresse",
    "h_km": "Km",
    "h_tarifa": "Tarif",
    "h_cena_km": "Preis/km",
    "h_start_taksa": "Grundgebühr",
    "h_ukupna_cena": "Gesamtpreis",
    "nema_servisa": "Keine Wartungseinträge in diesem Zeitraum.",
    "ukupno_servisi": "Insgesamt für Wartung ausgegeben im Zeitraum: {iznos}",
    "nema_troskova": "Keine sonstigen Ausgaben in diesem Zeitraum erfasst.",
    "ukupno_troskovi": "Sonstige Ausgaben insgesamt im Zeitraum: {iznos}",
    "prosek_potrosnje": "Durchschnittsverbrauch im Zeitraum: {prosek} l/100km ({litara} l auf {km} km)",
    "nema_potrosnje": "Für diesen Zeitraum wurde kein Verbrauch berechnet - es werden mindestens zwei aufeinanderfolgende Tankvorgänge mit eingetragenem Kilometerstand (Km an der Zapfsäule) benötigt, von denen der zweite in den gewählten Zeitraum fällt.",
    "ukupno_gorivo": "Insgesamt für Kraftstoff ausgegeben im Zeitraum: {iznos}",
    "ukupno_litara": "Liter insgesamt im Zeitraum: {litara} l",
    "nema_goriva": "Keine Tankeinträge in diesem Zeitraum.",
    "nema_voznji": "Keine Fahrten in diesem Zeitraum.",
    "ukupan_broj": "Gesamtzahl der Fahrten: {broj}",
    "ukupno_predjeno": "Gesamtstrecke (Fahrten): {km} km",
    "ukupna_zarada": "Gesamteinnahmen für den Zeitraum: {iznos}",
    "neto": "Netto (Einnahmen - Kraftstoff - Wartung - sonstige Ausgaben): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Übersicht",
    "sheet_voznje": "Fahrten",
    "sheet_gorivo": "Kraftstoff",
    "sheet_servisi": "Wartung",
    "sheet_troskovi": "Ausgaben",
    "podaci_vozaca": "Fahrerdaten",
    "zbirni_pregled": "Zusammenfassung (Formeln - siehe die anderen Blätter)",
    "x_ukupno_predjeno": "Gesamtstrecke (Fahrten)",
    "x_broj_voznji": "Anzahl der Fahrten",
    "x_bruto": "Bruttoeinnahmen (Fahrten)",
    "x_gorivo": "Kraftstoff (Kosten)",
    "x_litara": "   davon - Liter Kraftstoff",
    "x_servisi": "Wartung (Kosten)",
    "x_troskovi": "Sonstige Ausgaben",
    "x_neto": "NETTO (Bruttoeinnahmen - Kraftstoff - Wartung - sonstige Ausgaben)",
    "tip_benzin": "Benzin",
    "tip_tng": "LPG",
    "trosak_parking": "Parken",
    "trosak_putarina": "Maut",
    "trosak_pranje": "Waschen",
    "trosak_ostalo": "Sonstiges",
    "gps_napomena": "GPS-Fahrt (automatische Erfassung)",
}

RU = {
    "naslov_dnevno": "Дневной отчёт - {datum}",
    "naslov_nedeljno": "Недельный отчёт - с {pocetak} по {kraj}",
    "naslov_mesecno": "Месячный отчёт - {mesec}",
    "naslov_polug1": "Полугодовой отчёт - {godina} (январь-июнь)",
    "naslov_polug2": "Полугодовой отчёт - {godina} (июль-декабрь)",
    "naslov_godisnje": "Годовой отчёт - {godina}",
    "period": "Период: с {pocetak} по {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Имя и фамилия",
    "vozac_licenca": "Лицензия",
    "vozac_telefon": "Телефон",
    "vozac_vozilo": "Автомобиль",
    "vozac_tablice": "Номерной знак",
    "servisi_naslov": "Обслуживание авто за период",
    "troskovi_naslov": "Прочие расходы за период",
    "potrosnja_naslov": "Расход топлива",
    "gorivo_naslov": "Топливо - все записи за период",
    "voznje_naslov": "Поездки за период",
    "h_rbr": "№",
    "h_datum": "Дата",
    "h_vrsta_servisa": "Вид обслуживания",
    "h_kilometraza": "Пробег",
    "h_cena": "Цена",
    "h_napomena": "Примечание",
    "h_vrsta": "Вид",
    "h_predjeno": "Пройдено (с прошлой заправки)",
    "h_sipano": "Заправлено",
    "h_potrosnja": "Расход",
    "h_cena_sipanja": "Цена заправки",
    "h_litara": "Литры",
    "h_km_pumpa": "Пробег на заправке",
    "h_pocetak": "Начало",
    "h_kraj": "Конец",
    "h_adresa_polaska": "Адрес отправления",
    "h_adresa_dolaska": "Адрес назначения",
    "h_km": "Км",
    "h_tarifa": "Тариф",
    "h_cena_km": "Цена/км",
    "h_start_taksa": "Плата за посадку",
    "h_ukupna_cena": "Итоговая цена",
    "nema_servisa": "За этот период нет записей об обслуживании.",
    "ukupno_servisi": "Всего потрачено на обслуживание за период: {iznos}",
    "nema_troskova": "За этот период нет записей о прочих расходах.",
    "ukupno_troskovi": "Всего прочих расходов за период: {iznos}",
    "prosek_potrosnje": "Средний расход за период: {prosek} л/100км ({litara} л на {km} км)",
    "nema_potrosnje": "Расход за этот период не рассчитан - нужно как минимум две последовательные заправки с указанным пробегом (пробег на заправке), причём вторая приходится на выбранный период.",
    "ukupno_gorivo": "Всего потрачено на топливо за период: {iznos}",
    "ukupno_litara": "Всего литров за период: {litara} л",
    "nema_goriva": "За этот период нет записей о топливе.",
    "nema_voznji": "За этот период нет поездок.",
    "ukupan_broj": "Общее количество поездок: {broj}",
    "ukupno_predjeno": "Общее расстояние (поездки): {km} км",
    "ukupna_zarada": "Общий заработок за период: {iznos}",
    "neto": "Чистая прибыль (заработок - топливо - обслуживание - прочие расходы): {iznos}",
    "fmt_km": "{v} км",
    "fmt_l": "{v} л",
    "fmt_l100": "{v} л/100км",
    "u_km": "км",
    "u_l": "л",
    "sheet_pregled": "Обзор",
    "sheet_voznje": "Поездки",
    "sheet_gorivo": "Топливо",
    "sheet_servisi": "Обслуживание",
    "sheet_troskovi": "Расходы",
    "podaci_vozaca": "Данные водителя",
    "zbirni_pregled": "Сводка (формулы - см. другие листы)",
    "x_ukupno_predjeno": "Общее расстояние (поездки)",
    "x_broj_voznji": "Количество поездок",
    "x_bruto": "Валовый заработок (поездки)",
    "x_gorivo": "Топливо (расход)",
    "x_litara": "   из них - литров топлива",
    "x_servisi": "Обслуживание (расход)",
    "x_troskovi": "Прочие расходы",
    "x_neto": "ЧИСТАЯ ПРИБЫЛЬ (валовый заработок - топливо - обслуживание - прочие расходы)",
    "tip_benzin": "Бензин",
    "tip_tng": "Газ (LPG)",
    "trosak_parking": "Парковка",
    "trosak_putarina": "Платные дороги",
    "trosak_pranje": "Мойка",
    "trosak_ostalo": "Прочее",
    "gps_napomena": "GPS-поездка (автоматический ввод)",
}

PL = {
    "naslov_dnevno": "Raport dzienny - {datum}",
    "naslov_nedeljno": "Raport tygodniowy - od {pocetak} do {kraj}",
    "naslov_mesecno": "Raport miesięczny - {mesec}",
    "naslov_polug1": "Raport półroczny - {godina} (styczeń-czerwiec)",
    "naslov_polug2": "Raport półroczny - {godina} (lipiec-grudzień)",
    "naslov_godisnje": "Raport roczny - {godina}",
    "period": "Okres: od {pocetak} do {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Imię i nazwisko",
    "vozac_licenca": "Licencja",
    "vozac_telefon": "Telefon",
    "vozac_vozilo": "Pojazd",
    "vozac_tablice": "Tablica rejestracyjna",
    "servisi_naslov": "Serwis pojazdu w okresie",
    "troskovi_naslov": "Pozostałe koszty w okresie",
    "potrosnja_naslov": "Zużycie paliwa",
    "gorivo_naslov": "Paliwo - wszystkie wpisy w okresie",
    "voznje_naslov": "Przejazdy w okresie",
    "h_rbr": "Lp.",
    "h_datum": "Data",
    "h_vrsta_servisa": "Rodzaj serwisu",
    "h_kilometraza": "Przebieg",
    "h_cena": "Cena",
    "h_napomena": "Uwaga",
    "h_vrsta": "Rodzaj",
    "h_predjeno": "Przejechano (od ostatniego tankowania)",
    "h_sipano": "Zatankowano",
    "h_potrosnja": "Zużycie",
    "h_cena_sipanja": "Cena tankowania",
    "h_litara": "Litry",
    "h_km_pumpa": "Km na stacji",
    "h_pocetak": "Start",
    "h_kraj": "Koniec",
    "h_adresa_polaska": "Adres odbioru",
    "h_adresa_dolaska": "Adres docelowy",
    "h_km": "Km",
    "h_tarifa": "Taryfa",
    "h_cena_km": "Cena/km",
    "h_start_taksa": "Opłata startowa",
    "h_ukupna_cena": "Cena całkowita",
    "nema_servisa": "Brak wpisów serwisowych w tym okresie.",
    "ukupno_servisi": "Łącznie wydano na serwis w okresie: {iznos}",
    "nema_troskova": "Brak wpisanych pozostałych kosztów w tym okresie.",
    "ukupno_troskovi": "Łączne pozostałe koszty w okresie: {iznos}",
    "prosek_potrosnje": "Średnie zużycie w okresie: {prosek} l/100km ({litara} l na {km} km)",
    "nema_potrosnje": "Brak obliczonego zużycia dla tego okresu - potrzebne są co najmniej dwa kolejne tankowania z wpisanym przebiegiem (km na stacji), z których drugie przypada na wybrany okres.",
    "ukupno_gorivo": "Łącznie wydano na paliwo w okresie: {iznos}",
    "ukupno_litara": "Łącznie litrów w okresie: {litara} l",
    "nema_goriva": "Brak wpisów paliwa w tym okresie.",
    "nema_voznji": "Brak przejazdów w tym okresie.",
    "ukupan_broj": "Łączna liczba przejazdów: {broj}",
    "ukupno_predjeno": "Łączny dystans (przejazdy): {km} km",
    "ukupna_zarada": "Łączne zarobki za okres: {iznos}",
    "neto": "Netto (zarobki - paliwo - serwis - pozostałe koszty): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Podsumowanie",
    "sheet_voznje": "Przejazdy",
    "sheet_gorivo": "Paliwo",
    "sheet_servisi": "Serwis",
    "sheet_troskovi": "Koszty",
    "podaci_vozaca": "Dane kierowcy",
    "zbirni_pregled": "Podsumowanie zbiorcze (formuły - zobacz pozostałe arkusze)",
    "x_ukupno_predjeno": "Łączny dystans (przejazdy)",
    "x_broj_voznji": "Liczba przejazdów",
    "x_bruto": "Zarobki brutto (przejazdy)",
    "x_gorivo": "Paliwo (koszt)",
    "x_litara": "   w tym - litry paliwa",
    "x_servisi": "Serwis (koszt)",
    "x_troskovi": "Pozostałe koszty",
    "x_neto": "NETTO (zarobki brutto - paliwo - serwis - pozostałe koszty)",
    "tip_benzin": "Benzyna",
    "tip_tng": "LPG",
    "trosak_parking": "Parking",
    "trosak_putarina": "Opłaty drogowe",
    "trosak_pranje": "Mycie",
    "trosak_ostalo": "Inne",
    "gps_napomena": "Przejazd GPS (automatyczny wpis)",
}

TR = {
    "naslov_dnevno": "Günlük rapor - {datum}",
    "naslov_nedeljno": "Haftalık rapor - {pocetak} ile {kraj} arası",
    "naslov_mesecno": "Aylık rapor - {mesec}",
    "naslov_polug1": "Yarıyıllık rapor - {godina} (Ocak-Haziran)",
    "naslov_polug2": "Yarıyıllık rapor - {godina} (Temmuz-Aralık)",
    "naslov_godisnje": "Yıllık rapor - {godina}",
    "period": "Dönem: {pocetak} - {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Ad ve soyad",
    "vozac_licenca": "Lisans",
    "vozac_telefon": "Telefon",
    "vozac_vozilo": "Araç",
    "vozac_tablice": "Plaka",
    "servisi_naslov": "Dönemdeki araç servisi",
    "troskovi_naslov": "Dönemdeki diğer giderler",
    "potrosnja_naslov": "Yakıt tüketimi",
    "gorivo_naslov": "Yakıt - dönemdeki tüm kayıtlar",
    "voznje_naslov": "Dönemdeki yolculuklar",
    "h_rbr": "Sıra",
    "h_datum": "Tarih",
    "h_vrsta_servisa": "Servis türü",
    "h_kilometraza": "Kilometre",
    "h_cena": "Fiyat",
    "h_napomena": "Not",
    "h_vrsta": "Tür",
    "h_predjeno": "Katedilen (son yakıt alımından beri)",
    "h_sipano": "Alınan",
    "h_potrosnja": "Tüketim",
    "h_cena_sipanja": "Yakıt ücreti",
    "h_litara": "Litre",
    "h_km_pumpa": "Pompadaki km",
    "h_pocetak": "Başlangıç",
    "h_kraj": "Bitiş",
    "h_adresa_polaska": "Kalkış adresi",
    "h_adresa_dolaska": "Varış adresi",
    "h_km": "Km",
    "h_tarifa": "Tarife",
    "h_cena_km": "Fiyat/km",
    "h_start_taksa": "Açılış ücreti",
    "h_ukupna_cena": "Toplam fiyat",
    "nema_servisa": "Bu dönemde servis kaydı yok.",
    "ukupno_servisi": "Dönemde servise harcanan toplam: {iznos}",
    "nema_troskova": "Bu dönemde girilmiş başka gider yok.",
    "ukupno_troskovi": "Dönemdeki diğer giderlerin toplamı: {iznos}",
    "prosek_potrosnje": "Dönem ortalama tüketimi: {prosek} l/100km ({km} km'de {litara} l)",
    "nema_potrosnje": "Bu dönem için tüketim hesaplanamadı - kilometresi girilmiş (pompadaki km) en az iki ardışık yakıt alımı gerekir ve ikincisi seçilen döneme denk gelmelidir.",
    "ukupno_gorivo": "Dönemde yakıta harcanan toplam: {iznos}",
    "ukupno_litara": "Dönemdeki toplam litre: {litara} l",
    "nema_goriva": "Bu dönemde yakıt kaydı yok.",
    "nema_voznji": "Bu dönemde yolculuk yok.",
    "ukupan_broj": "Toplam yolculuk sayısı: {broj}",
    "ukupno_predjeno": "Toplam mesafe (yolculuklar): {km} km",
    "ukupna_zarada": "Dönem için toplam kazanç: {iznos}",
    "neto": "Net (kazanç - yakıt - servis - diğer giderler): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Özet",
    "sheet_voznje": "Yolculuklar",
    "sheet_gorivo": "Yakıt",
    "sheet_servisi": "Servis",
    "sheet_troskovi": "Giderler",
    "podaci_vozaca": "Sürücü bilgileri",
    "zbirni_pregled": "Genel özet (formüller - diğer sayfalara bakın)",
    "x_ukupno_predjeno": "Toplam mesafe (yolculuklar)",
    "x_broj_voznji": "Yolculuk sayısı",
    "x_bruto": "Brüt kazanç (yolculuklar)",
    "x_gorivo": "Yakıt (gider)",
    "x_litara": "   bunun - litre yakıt",
    "x_servisi": "Servis (gider)",
    "x_troskovi": "Diğer giderler",
    "x_neto": "NET (brüt kazanç - yakıt - servis - diğer giderler)",
    "tip_benzin": "Benzin",
    "tip_tng": "LPG",
    "trosak_parking": "Otopark",
    "trosak_putarina": "Geçiş ücreti",
    "trosak_pranje": "Yıkama",
    "trosak_ostalo": "Diğer",
    "gps_napomena": "GPS yolculuğu (otomatik giriş)",
}

ES = {
    "naslov_dnevno": "Informe diario - {datum}",
    "naslov_nedeljno": "Informe semanal - del {pocetak} al {kraj}",
    "naslov_mesecno": "Informe mensual - {mesec}",
    "naslov_polug1": "Informe semestral - {godina} (enero-junio)",
    "naslov_polug2": "Informe semestral - {godina} (julio-diciembre)",
    "naslov_godisnje": "Informe anual - {godina}",
    "period": "Período: del {pocetak} al {kraj}",
    "dvotacka": ": ",
    "vozac_ime": "Nombre y apellidos",
    "vozac_licenca": "Licencia",
    "vozac_telefon": "Teléfono",
    "vozac_vozilo": "Vehículo",
    "vozac_tablice": "Matrícula",
    "servisi_naslov": "Mantenimiento del vehículo en el período",
    "troskovi_naslov": "Otros gastos en el período",
    "potrosnja_naslov": "Consumo de combustible",
    "gorivo_naslov": "Combustible - todos los registros del período",
    "voznje_naslov": "Viajes del período",
    "h_rbr": "N.º",
    "h_datum": "Fecha",
    "h_vrsta_servisa": "Tipo de mantenimiento",
    "h_kilometraza": "Kilometraje",
    "h_cena": "Precio",
    "h_napomena": "Nota",
    "h_vrsta": "Tipo",
    "h_predjeno": "Recorrido (desde el último repostaje)",
    "h_sipano": "Repostado",
    "h_potrosnja": "Consumo",
    "h_cena_sipanja": "Precio del repostaje",
    "h_litara": "Litros",
    "h_km_pumpa": "Km en el surtidor",
    "h_pocetak": "Inicio",
    "h_kraj": "Fin",
    "h_adresa_polaska": "Dirección de recogida",
    "h_adresa_dolaska": "Dirección de destino",
    "h_km": "Km",
    "h_tarifa": "Tarifa",
    "h_cena_km": "Precio/km",
    "h_start_taksa": "Bajada de bandera",
    "h_ukupna_cena": "Precio total",
    "nema_servisa": "No hay registros de mantenimiento en este período.",
    "ukupno_servisi": "Total gastado en mantenimiento en el período: {iznos}",
    "nema_troskova": "No hay otros gastos introducidos en este período.",
    "ukupno_troskovi": "Total de otros gastos en el período: {iznos}",
    "prosek_potrosnje": "Consumo medio del período: {prosek} l/100km ({litara} l en {km} km)",
    "nema_potrosnje": "No se ha calculado el consumo para este período: hacen falta al menos dos repostajes consecutivos con kilometraje introducido (km en el surtidor), y el segundo debe caer dentro del período seleccionado.",
    "ukupno_gorivo": "Total gastado en combustible en el período: {iznos}",
    "ukupno_litara": "Total de litros en el período: {litara} l",
    "nema_goriva": "No hay registros de combustible en este período.",
    "nema_voznji": "No hay viajes en este período.",
    "ukupan_broj": "Número total de viajes: {broj}",
    "ukupno_predjeno": "Distancia total (viajes): {km} km",
    "ukupna_zarada": "Ganancias totales del período: {iznos}",
    "neto": "Neto (ganancias - combustible - mantenimiento - otros gastos): {iznos}",
    "fmt_km": "{v} km",
    "fmt_l": "{v} l",
    "fmt_l100": "{v} l/100km",
    "u_km": "km",
    "u_l": "l",
    "sheet_pregled": "Resumen",
    "sheet_voznje": "Viajes",
    "sheet_gorivo": "Combustible",
    "sheet_servisi": "Mantenimiento",
    "sheet_troskovi": "Gastos",
    "podaci_vozaca": "Datos del conductor",
    "zbirni_pregled": "Resumen general (fórmulas: véanse las demás hojas)",
    "x_ukupno_predjeno": "Distancia total (viajes)",
    "x_broj_voznji": "Número de viajes",
    "x_bruto": "Ganancias brutas (viajes)",
    "x_gorivo": "Combustible (gasto)",
    "x_litara": "   de los cuales - litros de combustible",
    "x_servisi": "Mantenimiento (gasto)",
    "x_troskovi": "Otros gastos",
    "x_neto": "NETO (ganancias brutas - combustible - mantenimiento - otros gastos)",
    "tip_benzin": "Gasolina",
    "tip_tng": "GLP",
    "trosak_parking": "Aparcamiento",
    "trosak_putarina": "Peajes",
    "trosak_pranje": "Lavado",
    "trosak_ostalo": "Otros",
    "gps_napomena": "Viaje con GPS (registro automático)",
}

TEKSTOVI = {
    "sr": SR,
    "en": EN,
    "it": IT,
    "fr": FR,
    "de": DE,
    "ru": RU,
    "pl": PL,
    "tr": TR,
    "es": ES,
}


def t(kljuc, **kwargs):
    """Vraca tekst za dati kljuc na trenutno izabranom jeziku (ako ga
    nema, srpski). Ako su prosledjeni parametri, zamenjuje {parametre}."""
    tekst = TEKSTOVI.get(jezici.get_current_language(), {}).get(kljuc)
    if tekst is None:
        tekst = SR.get(kljuc, kljuc)
    if kwargs:
        try:
            tekst = tekst.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return tekst


def _prevedi_sacuvanu_vrednost(vrednost, kljucevi):
    """Ako je 'vrednost' (npr. vrsta goriva sacuvana u bazi) identicna
    prevodu nekog od 'kljucevi' na BILO KOM jeziku, vraca prevod tog
    kljuca na trenutnom jeziku - tako se ispravno prikazuju i stari
    unosi. Inace vraca vrednost nepromenjenu."""
    if not vrednost:
        return vrednost
    for kljuc in kljucevi:
        for tabela in TEKSTOVI.values():
            if tabela.get(kljuc) == vrednost:
                return t(kljuc)
    return vrednost


def prevedi_tip_goriva(tip):
    """'Benzin' / 'TNG' (kako su sacuvani) -> naziv na trenutnom jeziku."""
    return _prevedi_sacuvanu_vrednost(tip, ("tip_benzin", "tip_tng"))


def prevedi_vrstu_troska(vrsta):
    """'Parking' / 'Putarina' / 'Pranje' / 'Ostalo' -> naziv na
    trenutnom jeziku. Bilo koja druga (rucno upisana) vrsta ostaje ista."""
    return _prevedi_sacuvanu_vrednost(
        vrsta,
        ("trosak_parking", "trosak_putarina", "trosak_pranje", "trosak_ostalo"),
    )


def prevedi_gps_napomenu(napomena):
    """Napomena koju app sama upise uz GPS voznju -> trenutni jezik."""
    return _prevedi_sacuvanu_vrednost(napomena, ("gps_napomena",))
