      - name: Fetch python-for-android (without full build yet)
        run: |
          yes | buildozer android p4a -- --help || true

      - name: Build APK with buildozer
        run: |
          yes | buildozer android debug
        env:
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
